apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ jenkins_maven_slave_pvc }}
labels:
  app: {{ jenkins_service }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi