spring:
  profiles: local
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/,http://localhost:8762/eureka/

---
spring:
  profiles: docker

eureka:
  client:
    service-url:
      defaultZone: http://service-registry-0:8761/eureka/,http://service-registry-1:8762/eureka/

---
spring:
  profiles: openshift
  
eureka:
  client:
    service-url:
      defaultZone: http://service-registry-0.svc:8761/eureka/,http://service-registry-1.svc:8761/eureka/
