management:
  endpoints:
    web.exposure.include: "*"
    health.show-details: always

eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${HOSTNAME:${spring.application.name}}:${server.port}
    startup: ${random.int}
    health-check-url-path: /actuator/health
  client:
    registryFetchIntervalSeconds: 5
---

spring:
  config:
    activate:
      on-profile: local

  zipkin:
    base-url: http://localhost:8086

  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

---
spring:
  config:
    activate:
      on-profile: openshift

  zipkin:
    base-url: http://zipkin:8080

  sleuth:
    sampler:
      probability: 1.0

  
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry-0.service-registry:8761/eureka/,http://service-registry-1.service-registry:8761/eureka/
  instance:
      instance-id: ${POD_NAME:${spring.application.name}}:${server.port}
      hostname: ${HOSTNAME:${spring.application.name}}
      
