server:
  port: 8080

spring:
  application:
    name: fraud-verifier
  cloud:
    loadbalancer:
      ribbon:
        enabled: false

---
spring:
  config:
    activate:
      on-profile: local

server:
  port: 8081
