eureka:
  instance:
    lease-renewal-interval-in-seconds: 10
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.cloud.client.ip-address}:${server.port}
  client:
    fetchRegistry: true
  server:
    enable-self-preservation: true
    
---
spring:
  profiles: local, docker
    
server:
  port: 8761
  
eureka:
  instance:
    hostname: service-registry-0
  client:
    serviceUrl:
      defaultZone: http://localhost:8762/eureka/

---
spring:
  profiles: local-1, docker-1
    
server:
  port: 8762
  
eureka:
  instance:
    hostname: service-registry-1
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
---
spring:
  profiles: openshift
    
server:
  port: 8761
  
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry-0.svc:8762/eureka/:http://service-registry-1.svc:8761/eureka/
