spring:
  application:
    name: service-registry

server:
  port: 8761
  
eureka:
  instance:
    prefer-ip-address: false
    instance-id: ${POD_NAME:${spring.application.name}}:${server.port}
    hostname: ${HOSTNAME:${spring.application.name}}
    lease-expiration-duration-in-seconds: 30
    lease-renewal-interval-in-seconds: 5
    health-check-url-path: /actuator/health
  server:
    enable-self-preservation: true
    eviction-interval-timer-in-ms: 5000
  client:
    register-with-eureka: true
    fetch-registry: true

logging:
  level:
    com:
      netflix:
        eureka: OFF
        discovery: OFF

---
spring:
  config:
    activate:
      on-profile: local
eureka:
  instance:
    prefer-ip-address: true
    hostname: ${spring.cloud.client.ip-address}:${server.port}
