apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: jenkins-edit
  namespace: {{ namespace }}
roleRef:
  kind: ClusterRole
  name: edit
  namespace: {{ namespace }}
subjects:
  - kind: ServiceAccount
    name: jenkins
    namespace: {{ namespace_tools }}
