spring:
  application:
    name: service-config
  profiles:
    active: native
    
server:
  port: 8888
 
management:
  endpoints:
    web.exposure.include=*

---
spring:
  profiles:
    activate: 
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo/
---
spring:
  profiles:
    activate: 
      on-profile: docker, openshift
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JonkeyGuan/spring-cloud-on-openshift
          search-paths: service/config/src/main/resources/config-repo
