spring:
  application:
    name: service-config
  profiles:
    active: native
    
management:
  endpoints:
    web.exposure.include=*

---
server:
  port: 8888

spring:
  config:
    activate:
      on-profile: native
  cloud:
    config:
      server:
        native:
          search-locations: classpath:/config-repo
---
server:
  port: 8888

spring:
  config:
    activate:
      on-profile: openshift
  cloud:
    config:
      server:
        git:
          uri: https://github.com/JonkeyGuan/spring-cloud-on-openshift
          search-paths: service-config/src/main/resources/config-repo
          default-label: main
          skipSslValidation: true
