spec:
  replicas: 2
  template:
    spec:
      containers:
        - env:
            - name: JAVA_OPTIONS
              value: "-Dspring.profiles.active=openshift"
            - name: AB_JOLOKIA_OFF
              value: "true"
          ports:
          - containerPort: 8888
            name: service
            protocol: TCP
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
              scheme: HTTP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: 8888
              scheme: HTTP
